### ISSUE TITLE
Show getter property value

### ISSUE THREAD

**Issue by f111fei** [Microsoft/vscode-chrome-debug-core#77]
When I use chrome debugger, I find variables can't show the getter property value. 

![qq 20160729214752](https://cloud.githubusercontent.com/assets/7069719/17250850/c9c741da-55d8-11e6-888e-e3a1ce5d8672.png)

related to https://github.com/Microsoft/vscode/pull/9949

**Comment by weinand** [comment]
I see the following two options (which both do not require additional debug protocol):
- auto resolve getters in the debug adapter (no UI gesture required),
- make the "property" node expandable so that the resolve happens lazily with the "expand" UI gesture. This functionality is almost identical to PR https://github.com/Microsoft/vscode/pull/9949 but it uses a UI metaphor that is already well known.

**Comment by roblourens** [comment]
Andre, 2 is a good idea, I hadn't thought of that. But if nobody is complaining about the node adapter auto resolving them, I'll probably copy that behavior.

**Comment by f111fei** [comment]
@weinand  idea 2 may be hard to Implement. Because the "expand" UI gesture is only to get the node's children, can not change this node self.

**Comment by weinand** [comment]
@f111fei the debug adapter is free to surface anything as a "child". So in case of a getter, the resolved value would become the child.

**Comment by f111fei** [comment]
@weinand 
If the getter result as getter property child, it make sense. Thanks for the answer.
