### ISSUE TITLE
Can't set breakpoint when using webpack cheap-module-eval-source-map 

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-chrome-debug-core#83]
In my vscode react boilerplate I got some responses that users can't set breakpoints. After some investigation it seems that some of the devtools options work cross-platform like `cheap-eval-source-map` but others don't. 
@roblourens hope you can help with this issue: https://github.com/skolmer/react-hot-boilerplate-vscode/issues/4

**Comment by roblourens** [comment]
Thanks for the heads up, I'll take a look when I get a chance.

**Comment by afhole** [comment]
I can only get it to work with `#source-map` (macOS 10.12.3, VS Code 1.9.1, Debugger for Chrome 2.5.3)

**Comment by roblourens** [comment]
Some of the other settings don't include enough info for a good debug experience, so I recommend `source-map`.

**Comment by skolmer** [comment]
@afhole @roblourens This configuration is working for me: https://github.com/skolmer/react-hot-boilerplate-vscode/commit/671807f79b702d5e3018112b0b0f563f3013aa57
I had to add the sourceMapPathOverrides configuration.

**Comment by afhole** [comment]
Unfortunately I already have `sourceMapPathOverrides` = #source-map doesn't even work without it

**Comment by auchenberg** [comment]
Our recommendation is to use either `cheap-module-source-map'` or `source-map` with Webpack in order to generate a working sourcemap.

The create-react-app project is using `cheap-module-source-map` and works with VS Code using the `sourceMapPathOverrides` .

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L43

**Comment by auchenberg** [comment]
Closing, as the `cheap-module-eval-source-map` doesn't provide enough information for VS Code.
